---
- hosts: all
  become: true
  tasks:
    - name: Add repository and install Nodejs
      shell: "curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs"

    - name: Install build-essential
      apt:
        name: build-essential
        state: present

    - name: Install pm2
      command: npm install pm2@latest -g

    - name: Install web server Nginx
      apt:
        name: nginx
        state: present

    - name: Delete default Nginx files
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Delete default Nginx files
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy Nginx configuration file
      copy:
        src: /tmp/nginx.conf
        dest: /etc/nginx/sites-available
        owner: www-data
        group: www-data
        mode: "644"

    - name: Create symbolic link of the Nginx configuration file
      file:
        src: /etc/nginx/sites-available/nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        state: link
