---
- hosts: all
  become: true
  tasks:
    - name: Añadir repositorio e instalar Nodejs
      shell: "curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs"

    - name: Instalar build-essential
      apt:
        name: build-essential
        state: present

    - name: Instalar pm2
      command: npm install pm2@latest -g

    - name: Instalar servidor web Nginx
      apt:
        name: nginx
        state: present

    - name: Eliminar archivos default de Nginx
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Eliminar archivos default de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copiar archivo configuración de Nginx
      copy:
        src: /tmp/nginx.conf
        dest: /etc/nginx/sites-available
        owner: www-data
        group: www-data
        mode: "644"

    - name: Crear enlace simbólico del archivo conf. de Nginx
      file:
        src: /etc/nginx/sites-available/nginx.conf
        dest: /etc/nginx/sites-enabled/nginx.conf
        state: link
